### PR TITLE
Fix/get online attance

### PR DESCRIPTION
**Pull request by HichamDz38**

### CODE REVIEW

**Review by 101t — APPROVED** [review]
💯

**Comment by HichamDz38** [comment]
thank you for validating the pull request
are you going to merge it?
i don't have right access to do that?

**Comment by 101t** [comment]
I added you as a collaborator to repo.

**Comment by HichamDz38** [comment]
i sill cannot merge it to the master, please merge it,
and by the way we need to disscuss about the pip package,
i added another one with different name, since the one created by :Yunkai Wang
is not updated, and Yunkai Wang is not responding,
i need to add you to the one that i create,

**Pull request merged**
